# Default configuration for AI-Generated Image Detection

# General settings
seed: 42
output_dir: "results"
log_level: "INFO"

# Data settings
data:
  root_dir: "data/genimage/imagenet_ai"
  batch_size: 32
  num_workers: 4
  pin_memory: true
  drop_last: false

# Model settings
model:
  type: "clip"  # Options: "resnet", "clip", "blip"
  name: "openai/clip-vit-base-patch32"
  mode: "fine-tune"  # Options: "zero-shot", "fine-tune"
  freeze_backbone: true
  num_classes: 2

# Training settings
training:
  # Optimization
  optimizer: "adamw"  # Options: "adam", "adamw", "sgd"
  learning_rate: 1e-4
  weight_decay: 0.01
  momentum: 0.9  # For SGD
  
  # Scheduler
  scheduler: "cosine"  # Options: "cosine", "step", "reduce_on_plateau"
  warmup_epochs: 1
  min_lr: 1e-6
  step_size: 2  # For step scheduler
  gamma: 0.1  # For step scheduler
  
  # Training loop
  num_epochs: 10
  grad_accumulation_steps: 1
  clip_grad_norm: 1.0
  mixed_precision: true
  
  # Checkpointing
  checkpoint_dir: "results/saved_models"
  save_frequency: 1
  
  # Early stopping
  early_stopping: true
  patience: 3
  
  # Logging
  log_frequency: 10  # Log every N steps
  use_tensorboard: true
  use_wandb: false  # Set to true to enable Weights & Biases

# Evaluation settings
evaluation:
  # Metrics to calculate
  metrics:
    - accuracy
    - auc
    - precision
    - recall
    - f1
    
  # Threshold settings
  threshold: 0.5
  optimize_threshold: true
  threshold_metric: "f1"
  
  # Output settings
  save_predictions: true
  predictions_file: "results/evaluation/predictions.csv"
  
  # Visualization
  generate_plots: true
  plot_dir: "results/figures"
  
  # Explainability
  generate_gradcam: false
  num_gradcam_samples: 16
  gradcam_layer: "visual.transformer.resblocks.11"

# Zero-shot settings (used when model.mode = "zero-shot")
zero_shot:
  prompts:
    - "a real photo"
    - "an AI-generated image"
  use_class_names: false  # If true, prompts become "a real photo of a {class}", etc.
  temperature: 1.0 