# Configuration for GXMA Fusion Detector Training

general:
  output_dir: "results/gxma_runs"  # Base directory for all outputs
  experiment_name: "gxma_fusion_poc"  # Subdirectory name for this run
  seed: 42
  gpu_id: 0  # GPU ID to use

model:
  hidden_dim: 256
  num_heads: 4
  num_classes: 2

data:
  base_data_dir: "/path/to/genimage_dataset/"  # UPDATE with actual dataset path
  train_samples_per_class: 5000
  val_samples_per_class: 500
  test_samples_per_class: 500
  batch_size: 8
  num_workers: 4
  class_to_idx:
    nature: 0
    ai: 1

training:
  optimizer: "adamw"
  learning_rate: 1e-4
  weight_decay: 0.0
  num_epochs: 10

evaluation:
  batch_size: 8
