# configs/prompt_tuning_instructblip_config.yaml

# Data Settings
data:
  train_path: "/path/to/train"
  val_test_path: "/path/to/val"
  num_train_samples: 200
  num_val_samples: 100
  num_test_samples: 50
  seed: 42

# Model Settings
model:
  name_pretrained: "Salesforce/instructblip-vicuna-7b"
  finetune_method: "prompt_tuning"
  prompt_tuning_params:
    num_virtual_tokens: 20
    init_text: "Is this image AI-generated?"

# Training Settings
training:
  should_train: true
  epochs: 5
  batch_size: 2
  eval_batch_size: 2
  learning_rate_prompt: 5.0e-3
  warmup_steps: 100
  weight_decay: 0.0
  evaluation_strategy: "steps"
  eval_steps: 50
  save_strategy: "steps"
  save_steps: 50
  save_total_limit: 5
  early_stopping_patience: 5
  early_stopping_threshold: 0.001
  gradient_accumulation_steps: 4
  use_bfloat16: true
  logging_steps: 10

# Output
output:
  base_results_dir_root: "results/instructblip_prompt_tuning"

# Environment Settings
environment:
  gpu_id: 0
  disable_wandb: true
