# Configuration for GXMA Fusion Detector Training

general:
  output_dir: "results/gxma_runs"  # Base directory for all outputs
  experiment_name: "gxma_sem_only_poc_genimage"  # Subdirectory name for this run
  seed: 42
  gpu_id: 1  # GPU ID to use

model:
  # Parameters for the GXMAFusionDetector model
  hidden_dim: 256
  num_heads: 4
  num_classes: 2

data:
  # 指向 POC 資料集根目錄
  base_data_dir: "/raid/dannyliu/dataset/GAI_Dataset/genimage/genimage_poc"
  # 指定各 split 名稱
  train_split_name: "train"
  val_split_name: "val"
  test_split_name: "test"  # 這會在訓練程式內作為預設 test loader
  # 若填 null 則表示取用該 split 內全部影像
  train_samples_per_class: null
  val_samples_per_class: null
  test_samples_per_class: null
  batch_size: 512
  num_workers: 4
  class_to_idx:
    nature: 0
    ai: 1

training:
  optimizer: "adamw"
  learning_rate: 1e-4
  weight_decay: 0.0
  num_epochs: 2000
  scheduler:
    name: "cosine_with_warmup"
    warmup_steps: 15
  early_stopping:
    monitor: "val_auc"  # 與主要指標一致

evaluation:
  batch_size: 512
  extra_tests:
    - name: "chameleon_poc"
      base_data_dir: "/raid/dannyliu/dataset/GAI_Dataset/chameleon_poc"
      split_name: ""  # 直接在根目錄下有 ai/nature
      class_to_idx:
        nature: 0
        ai: 1
