# Configuration for GXMA Parallel Fusion Detector Training (Strategy B)

general:
  output_dir: "results/gxma_runs"             # Base directory for all outputs
  experiment_name: "gxma_parallel_fusion_poc_genimage"  # Subdirectory name for this run
  seed: 42
  gpu_id: 1                                    # GPU ID to use

model:
  # Parameters for the GXMAFusionDetector model
  hidden_dim: 256
  num_heads: 4
  num_classes: 2
  freq_methods: ["radial", "dct", "wavelet"]  # 三種頻域特徵
  fusion_strategy: "parallel"                  # <- 新增：啟用 Strategy B

data:
  base_data_dir: "/raid/dannyliu/dataset/GAI_Dataset/genimage/genimage_poc"
  train_split_name: "train"
  val_split_name: "val"
  test_split_name: "test"
  train_samples_per_class: null
  val_samples_per_class: null
  test_samples_per_class: null
  batch_size: 1024
  num_workers: 4
  class_to_idx:
    nature: 0
    ai: 1

training:
  optimizer: "adamw"
  learning_rate: 1e-4
  weight_decay: 0.0
  num_epochs: 2000
  scheduler:
    name: "cosine_with_warmup"
    warmup_steps: 15
  early_stopping:
    monitor: "val_auc"
    patience: 40
    threshold: 0.001

evaluation:
  batch_size: 1024
  extra_tests:
    - name: "chameleon_poc"
      base_data_dir: "/raid/dannyliu/dataset/GAI_Dataset/chameleon_poc"
      split_name: ""
      class_to_idx:
        nature: 0
        ai: 1 